name: Trivy FS secret scan
on:
  workflow_call:

jobs:
  trivy_fs_secret_scan:
    name: Trivy FS secret scan
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      # this doesnt detect deleted files in history
      # with:
      #   fetch-depth: 0

    # trivy -q fs ./ --scanners secret --exit-code 1
    # https://github.com/aquasecurity/trivy-action
    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        # trivy-config: trivy.yaml
        scanners: 'secret'
        exit-code: '1'
